### ISSUE TITLE
Error when using with `networkx` module

### ISSUE THREAD

**Issue by goyalyashpal** [wookayin/python-imgcat#16]
- I can't seem to get these 3 things (a.) `networkx` (b.) `matplotlib.pyplot` (c.) `imgcat` to work together... (ab) work together well verified, (bc) work together per the imagecat documentation, (c) alone work well verified... but how to get (abc) to work 😅 ?
- I am pretty sure i am making some silly mistake, but can't figure out.

```python
# Works Well
from imgcat import imgcat
imgcat(open("Figure_1.png"))
```

I was thinking maybe there's some way to `plt.savefig()` to some variable then render that via `imgcat()` but that doesn't seeem to work either...

```python
import matplotlib
matplotlib.use("module://imgcat")

import networkx as nx
import matplotlib.pyplot as plt
# from imgcat import imgcat

edges = [(1,2),(2,3),(2,4)]

nxgraph = nx.Graph()
nxgraph.add_edges_from(edges)

nx.draw_networkx(nxgraph)
# fig = nx.draw_networkx(nxgraph)
plt.show()
# plt.savefig()
# imgcat(fig)
```

<details>
<summary>Show Stack Trace Back</summary>

<br/>

```error
Traceback (most recent call last):
  File "<DIR>\nx-pydot-graphviz-imgcat.py", line 15, in <module>
    nx.draw_networkx(nxgraph)
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\networkx\drawing\nx_pylab.py", line 303, in draw_networkx
    draw_networkx_nodes(G, pos, **node_kwds)
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\networkx\drawing\nx_pylab.py", line 416, in draw_networkx_nodes
    ax = plt.gca()
         ^^^^^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\pyplot.py", line 2309, in gca
    return gcf().gca()
           ^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\pyplot.py", line 906, in gcf
    return figure()
           ^^^^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\pyplot.py", line 861, in figure
    draw_if_interactive()
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\pyplot.py", line 397, in draw_if_interactive
    return _get_backend_mod().draw_if_interactive(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\backend_bases.py", line 3583, in draw_if_interactive
    manager_class = cls.FigureCanvas.manager_class
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'manager_class'
```

</details>

**Comment by goyalyashpal** [comment]
```
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\pyplot.py", line 861, in figure
    draw_if_interactive()
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\pyplot.py", line 397, in draw_if_interactive
    return _get_backend_mod().draw_if_interactive(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramFiles\Python\Python311\Lib\site-packages\matplotlib\backend_bases.py", line 3583, in draw_if_interactive
    manager_class = cls.FigureCanvas.manager_class
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```


based on these lines mentioning: `deprecation.py`, `draw_if_interactive()`, `FigureCanvas`
it seems it's related with https://github.com/wookayin/python-imgcat/issues/13

**Comment by goyalyashpal** [comment]
> I was thinking maybe there's some way to `plt.savefig()` to some variable then render that via `imgcat()` but that doesn't seeem to work either...

in the meantime, can someone please help me getting that way to work 😅 
I don't want to output to actual image... as that would require cleaning it up later, and i am afraid that in deleting smth, i would maybe mess up and delete some thing else...

**Comment by goyalyashpal** [comment]
```python
from imgcat import imgcat

import networkx as nx
import matplotlib.pyplot as plt

edges = [(1,2),(2,3),(2,4)]

nxgraph = nx.Graph()
nxgraph.add_edges_from(edges)

nx.draw_networkx(nxgraph)

# plt.show()

plt.savefig('outputGraph.png', dpi=100, bbox_inches='tight')
imgcat(open('outputGraph.png'))

```

**Comment by goyalyashpal** [comment]
```python
from imgcat import imgcat

import networkx as nx
import matplotlib.pyplot as plt

edges = [(1,2),(2,3),(2,4)]

nxgraph = nx.Graph()
nxgraph.add_edges_from(edges)

nx.draw_networkx(nxgraph)

# fig = plt.figure(1)
# imgcat(fig)
imgcat(plt.figure(1))

```
